package com.aura.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import com.aura.R

private val AuraFontFamily = FontFamily(
    Font(R.font.jetbrains_mono_thin, FontWeight.Thin),
    Font(R.font.jetbrains_mono_regular, FontWeight.Normal),
    Font(R.font.jetbrains_mono_medium, FontWeight.Medium),
    Font(R.font.jetbrains_mono_semibold, FontWeight.SemiBold),
    Font(R.font.jetbrains_mono_bold, FontWeight.Bold),
)

private val AuraDisplayFamily = FontFamily(
    Font(R.font.space_grotesk_light, FontWeight.Light),
    Font(R.font.space_grotesk_regular, FontWeight.Normal),
    Font(R.font.space_grotesk_medium, FontWeight.Medium),
    Font(R.font.space_grotesk_bold, FontWeight.Bold),
)

@Immutable
data class AuraTypography(
    val logo: TextStyle,
    val cardLabel: TextStyle,
    val displayNumber: TextStyle,
    val counterNumber: TextStyle,
    val unitLabel: TextStyle,
    val timer: TextStyle,
    val title: TextStyle,
    val body: TextStyle,
    val caption: TextStyle,
    val badge: TextStyle,
    val navLabel: TextStyle,
    val stepLabel: TextStyle,
    val brandTitle: TextStyle,
    val brandTagline: TextStyle,
    val segmentLabel: TextStyle,
    val fieldLabel: TextStyle,
    val fieldText: TextStyle,
    val actionLabel: TextStyle,
    val primaryButtonLabel: TextStyle,
    val secondaryButtonLabel: TextStyle,
    val linkLabel: TextStyle,
    val legalLabel: TextStyle,
    val screenHeading: TextStyle,
    val screenSubheading: TextStyle,
    val screenHint: TextStyle,
    val chipLabel: TextStyle,
    val consoleLine: TextStyle,
    val inviteCode: TextStyle,
    val bonusValue: TextStyle,
    val bonusUnit: TextStyle,
    val sheetHeading: TextStyle,
    val sheetBody: TextStyle,
    val sheetActionLabel: TextStyle,
    val cardTitle: TextStyle,
    val metricNumber: TextStyle,
    val dataValue: TextStyle,
    val speedValue: TextStyle,
    val gaugeLabel: TextStyle,
    val latestValue: TextStyle,
    val logNumber: TextStyle,
    val cardCaption: TextStyle,
    val cardUnit: TextStyle,
    val cardNote: TextStyle,
    val listValue: TextStyle,
    val listRowTitle: TextStyle,
    val bracket: TextStyle,
    val sectionTitle: TextStyle,
)

val AuraDefaultTypography = AuraTypography(
    logo = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 19.sp,
        lineHeight = 24.sp,
        letterSpacing = 1.4.sp,
    ),
    cardLabel = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.SemiBold,
        fontSize = 10.sp,
        lineHeight = 13.2.sp,
        letterSpacing = 0.12.sp,
    ),
    displayNumber = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 24.sp,
        lineHeight = 30.6.sp,
        letterSpacing = 0.sp,
    ),
    counterNumber = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 16.sp,
        lineHeight = 20.4.sp,
        letterSpacing = 0.sp,
    ),
    unitLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 10.sp,
        lineHeight = 12.8.sp,
        letterSpacing = 0.sp,
    ),
    timer = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 22.sp,
        lineHeight = 29.sp,
        letterSpacing = 0.22.sp,
    ),
    title = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 15.3.sp,
        letterSpacing = 0.sp,
    ),
    body = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 15.3.sp,
        letterSpacing = 0.sp,
    ),
    caption = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 10.sp,
        lineHeight = 13.2.sp,
        letterSpacing = 0.sp,
    ),
    badge = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 15.8.sp,
        letterSpacing = 0.sp,
    ),
    navLabel = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.SemiBold,
        fontSize = 10.sp,
        lineHeight = 13.2.sp,
        letterSpacing = 0.sp,
    ),
    stepLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 10.sp,
        lineHeight = 12.8.sp,
        letterSpacing = 0.sp,
    ),
    brandTitle = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 30.sp,
        lineHeight = 38.3.sp,
        letterSpacing = 0.5.sp,
    ),
    brandTagline = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 15.3.sp,
        letterSpacing = 0.3.sp,
    ),
    segmentLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 15.3.sp,
        letterSpacing = 0.sp,
    ),
    fieldLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 9.sp,
        lineHeight = 11.5.sp,
        letterSpacing = 1.2.sp,
    ),
    fieldText = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 17.9.sp,
        letterSpacing = 0.sp,
    ),
    actionLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 15.sp,
        lineHeight = 19.1.sp,
        letterSpacing = 0.sp,
    ),
    primaryButtonLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 15.sp,
        lineHeight = 19.1.sp,
        letterSpacing = 0.sp,
    ),
    secondaryButtonLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 17.9.sp,
        letterSpacing = 0.sp,
    ),
    linkLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 15.3.sp,
        letterSpacing = 0.sp,
    ),
    legalLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 10.sp,
        lineHeight = 12.8.sp,
        letterSpacing = 0.sp,
    ),
    screenHeading = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 24.sp,
        lineHeight = 30.6.sp,
        letterSpacing = 0.sp,
    ),
    screenSubheading = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 13.sp,
        lineHeight = 16.6.sp,
        letterSpacing = 0.sp,
    ),
    screenHint = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 11.sp,
        lineHeight = 14.sp,
        letterSpacing = 0.sp,
    ),
    chipLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 10.sp,
        lineHeight = 12.8.sp,
        letterSpacing = 1.sp,
    ),
    consoleLine = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 15.8.sp,
        letterSpacing = 0.sp,
    ),
    inviteCode = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 22.4.sp,
        letterSpacing = 3.sp,
    ),
    bonusValue = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 30.sp,
        lineHeight = 39.6.sp,
        letterSpacing = 1.sp,
    ),
    bonusUnit = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 15.8.sp,
        letterSpacing = 0.sp,
    ),
    sheetHeading = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 18.sp,
        lineHeight = 23.sp,
        letterSpacing = 0.sp,
    ),
    sheetBody = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 15.sp,
        lineHeight = 19.1.sp,
        letterSpacing = 0.sp,
    ),
    sheetActionLabel = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 16.sp,
        lineHeight = 20.4.sp,
        letterSpacing = 0.sp,
    ),
    cardTitle = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 16.sp,
        lineHeight = 20.4.sp,
        letterSpacing = 0.sp,
    ),
    metricNumber = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 24.sp,
        lineHeight = 31.7.sp,
        letterSpacing = 0.sp,
    ),
    dataValue = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 16.sp,
        lineHeight = 21.1.sp,
        letterSpacing = 0.16.sp,
    ),
    speedValue = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 32.sp,
        lineHeight = 42.2.sp,
        letterSpacing = 0.sp,
    ),
    gaugeLabel = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 12.sp,
        lineHeight = 15.8.sp,
        letterSpacing = 0.096.sp,
    ),
    latestValue = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 15.8.sp,
        letterSpacing = 0.sp,
    ),
    logNumber = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Normal,
        fontSize = 10.sp,
        lineHeight = 13.2.sp,
        letterSpacing = 0.08.sp,
    ),
    cardCaption = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Light,
        fontSize = 10.sp,
        lineHeight = 13.sp,
        letterSpacing = 0.sp,
    ),
    cardUnit = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Bold,
        fontSize = 10.sp,
        lineHeight = 13.sp,
        letterSpacing = 0.sp,
    ),
    cardNote = TextStyle(
        fontFamily = AuraDisplayFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 10.sp,
        lineHeight = 13.sp,
        letterSpacing = 0.sp,
    ),
    listValue = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 10.sp,
        lineHeight = 13.sp,
        letterSpacing = 0.08.sp,
    ),
    listRowTitle = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 18.sp,
        letterSpacing = 0.112.sp,
    ),
    bracket = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Thin,
        fontSize = 16.sp,
        lineHeight = 21.sp,
        letterSpacing = 0.sp,
    ),
    sectionTitle = TextStyle(
        fontFamily = AuraFontFamily,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.sp,
    ),
)
