package com.aura.feature.transactions.presentation.preview

import com.aura.feature.transactions.domain.model.TransactionEvent
import com.aura.feature.transactions.domain.model.TransactionKind
import com.aura.feature.transactions.presentation.TransactionsUiState
import java.util.Calendar

private fun eventAt(day: Int, hour: Int, minute: Int): Long =
    Calendar.getInstance().apply {
        set(2026, Calendar.JULY, day, hour, minute, 0)
        set(Calendar.MILLISECOND, 0)
    }.timeInMillis

object TransactionsPreviewData {

    val events = listOf(
        TransactionEvent(
            id = "1",
            timestamp = eventAt(10, 8, 14),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "2",
            timestamp = eventAt(10, 8, 14),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "3",
            timestamp = eventAt(10, 13, 2),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "1.4 GB · Mobile",
            amount = "+610 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "4",
            timestamp = eventAt(10, 21, 47),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "2.0 GB · Wi-Fi",
            amount = "+910 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "5",
            timestamp = eventAt(9, 21, 2),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "6",
            timestamp = eventAt(9, 21, 2),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "7",
            timestamp = eventAt(8, 13, 47),
            kind = TransactionKind.REFERRAL,
            typeLabel = "Referral Bonus",
            fieldKey = "from",
            fieldValue = "@alexk",
            amount = "+1,240 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "8",
            timestamp = eventAt(8, 19, 15),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "0.8 GB · Wi-Fi",
            amount = "+340 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "9",
            timestamp = eventAt(7, 9, 30),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "5.0 GB · Mobile",
            amount = "+2,180 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "10",
            timestamp = eventAt(7, 14, 5),
            kind = TransactionKind.EXCHANGE,
            typeLabel = "Exchange",
            fieldKey = "for",
            fieldValue = "promo code",
            amount = "−110 ION",
            isCredit = false,
        ),
        TransactionEvent(
            id = "11",
            timestamp = eventAt(7, 18, 40),
            kind = TransactionKind.EXCHANGE,
            typeLabel = "Exchange",
            fieldKey = "for",
            fieldValue = "promo code",
            amount = "−240,000 Spark",
            isCredit = false,
        ),
        TransactionEvent(
            id = "12",
            timestamp = eventAt(6, 8, 22),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "13",
            timestamp = eventAt(6, 8, 22),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "14",
            timestamp = eventAt(6, 12, 40),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "1.2 GB · Wi-Fi",
            amount = "+520 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "15",
            timestamp = eventAt(6, 19, 5),
            kind = TransactionKind.REFERRAL,
            typeLabel = "Referral Bonus",
            fieldKey = "from",
            fieldValue = "@mira",
            amount = "+1,240 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "16",
            timestamp = eventAt(6, 22, 10),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "3.1 GB · Mobile",
            amount = "+1,350 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "17",
            timestamp = eventAt(5, 7, 52),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "18",
            timestamp = eventAt(5, 7, 52),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "19",
            timestamp = eventAt(5, 11, 18),
            kind = TransactionKind.EXCHANGE,
            typeLabel = "Exchange",
            fieldKey = "for",
            fieldValue = "promo code",
            amount = "−110 ION",
            isCredit = false,
        ),
        TransactionEvent(
            id = "20",
            timestamp = eventAt(5, 16, 44),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "0.6 GB · Wi-Fi",
            amount = "+260 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "21",
            timestamp = eventAt(4, 9, 5),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "22",
            timestamp = eventAt(4, 9, 5),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "23",
            timestamp = eventAt(4, 14, 27),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "2.4 GB · Mobile",
            amount = "+1,040 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "24",
            timestamp = eventAt(4, 20, 33),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "1.1 GB · Wi-Fi",
            amount = "+470 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "25",
            timestamp = eventAt(4, 21, 50),
            kind = TransactionKind.REFERRAL,
            typeLabel = "Referral Bonus",
            fieldKey = "from",
            fieldValue = "@kirov",
            amount = "+1,240 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "26",
            timestamp = eventAt(3, 8, 41),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "27",
            timestamp = eventAt(3, 8, 41),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "28",
            timestamp = eventAt(3, 13, 9),
            kind = TransactionKind.EXCHANGE,
            typeLabel = "Exchange",
            fieldKey = "for",
            fieldValue = "promo code",
            amount = "−240,000 Spark",
            isCredit = false,
        ),
        TransactionEvent(
            id = "29",
            timestamp = eventAt(3, 18, 20),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "4.2 GB · Mobile",
            amount = "+1,830 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "30",
            timestamp = eventAt(2, 10, 12),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "31",
            timestamp = eventAt(2, 10, 12),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "32",
            timestamp = eventAt(2, 15, 55),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "0.9 GB · Wi-Fi",
            amount = "+390 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "33",
            timestamp = eventAt(2, 21, 30),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "1.7 GB · Mobile",
            amount = "+740 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "34",
            timestamp = eventAt(1, 9, 47),
            kind = TransactionKind.ION,
            typeLabel = "ION",
            fieldKey = "source",
            fieldValue = "home_button",
            amount = "+20 ION",
            isCredit = true,
        ),
        TransactionEvent(
            id = "35",
            timestamp = eventAt(1, 9, 47),
            kind = TransactionKind.SPARK,
            typeLabel = "Spark",
            fieldKey = "source",
            fieldValue = "home_button_accrual",
            amount = "+40,000 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "36",
            timestamp = eventAt(1, 14, 2),
            kind = TransactionKind.REFERRAL,
            typeLabel = "Referral Bonus",
            fieldKey = "from",
            fieldValue = "@dana",
            amount = "+1,240 Spark",
            isCredit = true,
        ),
        TransactionEvent(
            id = "37",
            timestamp = eventAt(1, 19, 38),
            kind = TransactionKind.EXCHANGE,
            typeLabel = "Exchange",
            fieldKey = "for",
            fieldValue = "promo code",
            amount = "−110 ION",
            isCredit = false,
        ),
        TransactionEvent(
            id = "38",
            timestamp = eventAt(1, 23, 5),
            kind = TransactionKind.DATA_SHARE,
            typeLabel = "Data Share",
            fieldKey = "given",
            fieldValue = "2.8 GB · Wi-Fi",
            amount = "+1,210 ION",
            isCredit = true,
        ),
    )

    val content = TransactionsUiState(
        handle = "syrex",
        events = events,
    )

    val empty = TransactionsUiState(handle = "syrex")
}
